spring:
  datasource:
    url: jdbc:mariadb://192.168.35.54:3306/minicampus2
    driver-class-name: org.mariadb.jdbc.Driver
    username: minicampus2_user
    password: a1234

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: sin99145@gmail.com
    password: jadbysjtlcvhpkdn
    properties:
      mail:
        smtp:
          starttls:
            enable: true

logging:
  level:
    root: info
    
mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
